apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flask-app-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: flask-app-secret
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: secret/database
      property: password