apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-external-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: database-secret
  data:
  - secretKey: username
    remoteRef:
      key: secret/database
      property: username
  - secretKey: password
    remoteRef:
      key: secret/database
      property: password