apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  labels:
    app: student-api
spec:
  selector:
    app: student-api
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
