version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: student_db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask-app:
    build: .
    container_name: student_api
    ports:
      - "3000:${PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

secrets:
  postgres_password:
    file: ./postgres_password

volumes:
  postgres_data:
