apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: {{ .Values.vault.image }}
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: {{ .Values.vault.rootToken }}
        command: ["vault", "server", "-dev"]
        ports:
        - containerPort: {{ .Values.vault.port }}