---
apiVersion: v1
kind: Namespace
metadata:
  name: student-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: student-api
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: secret/database
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: secret/database
      property: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: student-api
data:
  POSTGRES_DB: "student_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: student-api
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
      nodeSelector:
        node-type: "database"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: student-api
spec:
  selector:
    app: postgres
  ports:
  - port: 5432