---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    storage "file" {
      path = "/vault/data"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = true
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment
  namespace: vault
spec:
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.15.0
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "root-token"
        command: ["vault"]
        args: ["server", "-dev"]
      nodeSelector:
        node-type: "dependent-service"
---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: vault
spec:
  selector:
    app: vault
  ports:
  - port: 8200