apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-rules
  namespace: observability
data:
  alert-rules.yml: |
    groups:
    - name: basic-alerts
      rules:
      - alert: ServiceDown
        expr: probe_success == 0
        for: 1m
        annotations:
          summary: "Service is down"