apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-exporter-secret
  namespace: observability
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-exporter-secret
  data:
  - secretKey: data_source_name
    remoteRef:
      key: secret/database
      property: connection_string