apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      nodeSelector:
        node-type: "database"
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:latest
        ports:
        - containerPort: 9187
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretRef:
              name: postgres-exporter-secret
              key: data_source_name
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: observability
spec:
  selector:
    app: postgres-exporter
  ports:
  - port: 9187
    targetPort: 9187
  type: ClusterIP