apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.serviceAccount.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceAccount.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceAccount.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: external-secrets
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}