apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:17
        env:
        - name: POSTGRES_PASSWORD
          value: postgres123
        - name: POSTGRES_DB
          value: student_db