name: setup-a-ci-pipeline4

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ["self-hosted", "macOS", "ARM64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verifying the self-hosted runners
        run: echo " OK"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and Start Services
        run: docker-compose up -d --build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST_AUTH_METHOD: ${{ secrets.POSTGRES_HOST_AUTH_METHOD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Run the health check test
        run: |
            pip install requests
            cd tests
            python3 test_students.py -v

      - name: Code linting
        run: ruff check --fix --exit-zero --quiet

      - name: Docker hub login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Image Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-bootcamp-assignments-flask-app:latest
